export * from "./about";
export * from "./contact";
export * from "./footer";
export * from "./header";
export * from "./hero";
export * from "./hero";
export * from "./projects";
export * from "./tape";
export * from "./testimonials";
